# Site settings
title: Robert Kenny's Portfolio 
description: A personal portfolio site that displays relevant information about myself!

# User settings
username: Robert Kenny
user_description: I am a Computer Science Student at California State University Fullerton.
user_title: Computer Science Student 
email: rlkenny@csu.fullerton.edu
twitter_username: rkenny98
github_username:  rlkenny98
